services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: web
      ME_CONFIG_MONGODB_ADMINPASSWORD: web1234
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin1234@mongodb:27017/admin?serverSelectionTimeoutMS=1000000
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
